config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'
  get 'lists/new', to: 'lists#new'
  get 'lists/:id', to: 'lists#show', as: 'list'
  post '/lists', to: 'lists#create'

  get 'lists/:id/bookmarks/new', to: 'bookmarks#new', as: 'list_bookmarks'
  post 'lists/:id/bookmarks/new', to: 'bookmarks#create'

  delete 'lists/:id/bookmarks', to: 'bookmarks#destroy', as: 'list_bookmarks_delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true

  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def create
    data = fetch_movie_data
    @list = List.find(params[:id])
    if data['results'].empty?
      flash[:notice] = 'Sorry, but something went wrong with your search.'
      redirect_to list_path(@list)
      return
    end
    movie = get_movie_data(data)

    if Movie.exists?(title: movie[:title])
      @movie = Movie.find_by(title: movie[:title])
    else
      @movie = Movie.create(movie)
    end

    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:id])
    @bookmark.list = @list
    @bookmark.movie = @movie

    if @bookmark.valid?
      @bookmark.save
      flash[:notice] = ''
      redirect_to list_path(@list)
    else
      flash[:notice] = 'Your comment must be 6 characters minimum.'
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end

  def fetch_movie_data
    encoded_search = CGI.escape(params[:bookmark][:movie])
    search = URI.parse(encoded_search).to_s
    url = "https://api.themoviedb.org/3/search/movie?query=#{search}&include_adult=false&language=en-US&page=1"
    options = { 'Authorization' => "Bearer #{ENV['TMDB_ACCESS_TOKEN']}", 'accept' => 'application/json' }

    response = URI.open(url, options).read
    JSON.parse(response)
  end

  def get_movie_data(data)
    title = data['results'].first['title']
    overview = data['results'].first['overview']
    poster_url = "https://image.tmdb.org/t/p/original/#{data['results'].first['poster_path']}"
    rating = data['results'].first['vote_average'].to_f.round(1)
    { title: title, overview: overview, poster_url: poster_url, rating: rating }
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit 'Add a movie' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<nav class="navbar bg-body-tertiary sticky-top" style="padding-inline: 2em;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fa-solid fa-film"></i>
    </a>
  </div>
</nav>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Interno_di_un_sala_da_cinema.JPG/1200px-Interno_di_un_sala_da_cinema.JPG);">
  <div class="container" style="text-align: center;">
    <h1>Watch-list</h1>
  </div>
</div>
<div class="container container-custom-2" data-controller="toggle">
  <div class="add-btn-container">
    <div class="btn btn-success" style="float: right; color: white" data-action="click->toggle#showCreateListForm">Create movie list</div>
  </div>
  <div class="cards">
  <% @lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>'); position: relative;">
    <%= link_to ' ', list_path(list), style: 'width: 100%; height: 100%; position: absolute;' %>
      <%= list.name %>
    </div>
  <% end %>
  </div>
  <div data-toggle-target="createListForm" class="d-none" style="align-self: center;">
    <%= simple_form_for @list, html: { style: 'width: 50em; margin-block: 3em;' } do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit 'Create list', class: 'btn btn-success', style: 'color: white;' %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<nav class="navbar bg-body-tertiary sticky-top" style="padding-inline: 2em;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fa-solid fa-film"></i>
    </a>
    <%= link_to "My Lists", root_path, style: "color: black; text-decoration: none;" %>
  </div>
</nav>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>');">
  <div class="container" style="text-align: center;">
    <h1><%= @list.name %></h1>
    <div class="btn btn-warning" style="position: absolute; right: 2em; top: 2em; color: white;"><%= @list.movies.count %> movies</div>
  </div>
</div>
<div class="container container-custom" data-controller="toggle">
  <div class="add-btn-container">
    <div class="btn btn-success" style="position: absolute; right: 0; color: white" data-action="click->toggle#showAddMovieForm">Add a Movie</div>
    <% if flash[:notice] != "" %>
      <div class="text-danger animation-warning-background" style="padding: 0 3em; border-radius: 4px;"><%= "#{flash[:notice]}" %></div>
    <% end %>
  </div>
  <div class="row row-cols-2 cards-movie-container-custom">
    <% @list.bookmarks.each do |bookmark| %>
    <div class="card card-movie-custom" style="width: 32rem;">
      <%= image_tag(bookmark.movie.poster_url, class: "card-img-top") %>
      <div class="card-body">
        <div class="card-title-and-rating-container">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p> • <%= bookmark.movie.rating %></p>
          <i class="fa-solid fa-star" style="color: #ffcb00; height: 1.5em; margin-left: .2em;"></i>
        </div>
        <p class="card-text"><%= bookmark.movie.overview[..150] %> ...</p>
        <div style="display: flex; justify-content: space-between;">
          <div style="display: flex; align-items: center;">
            <i class="fa-solid fa-quote-left" style="font-size: 1.5em;">
            </i>
            <p style="margin-bottom: 0; margin-left: .7em; font-weight: bold;"><%= bookmark.comment %></p>
          </div>
          <%= link_to "Delete", list_bookmarks_delete_path(bookmark), class: "text-danger",
          data: {turbo_method: :delete}%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div data-toggle-target="addMovieForm" style="align-self: center;">
    <%= simple_form_for [@list, @bookmark], html: { style: 'width: 50em; margin-block: 3em;' } do |f| %>
      <%= f.input :movie, hint: 'No special characters.' %>
      <%= f.input :comment %>
      <%= f.submit 'Add movie', class: 'btn btn-success', style: 'color: white;' %>
    <% end %>
  </div>
</div>